config/routes.rb
Rails.application.routes.draw do
  resource :excluded_data, only: [:show] do
    resources :farmers, only: [:index], module: :excluded_data
    resources :production_unities, only: [:index], module: :excluded_data
    resources :groups, only: [:index], module: :excluded_data
  end

  # Help
  get '/help/reduce_pdf_size'

  get 'document_access_visualizations/core'

  get 'document_access_visualizations/group'

  get 'document_access_visualizations/documents_farmers_and_production_unities'

  get 'document_access_visualizations/farmer'

  get 'document_access_visualizations/production_unity'

  get 'document_access_visualizations/certificate'

  resources :document_visualizations
  get "/home/search" => "home#search"
  get "/home/report" => "home#report"
  resource :user_sessions
  resource :document_visualization_sessions

  namespace :view_reports do
    get '/view_reports' => 'view_reports#index'
    get '/farmer_reports' => 'farmer_reports#index'
    get '/product_reports' => 'product_reports#index'
    get '/city_reports' => 'city_reports#index'
    get '/production_unity_reports' => 'production_unity_reports#index'
  end

  namespace :reports do
    get 'index'
    get 'quantity'
    get 'annuity'
    get 'certified_members'

    get '/core_reports/actual_situation' => 'core_reports#actual_situation'
    get '/core_reports/products' => 'core_reports#products'
    get '/global_reports/actual_situation' => 'global_reports#actual_situation'
    get '/global_reports/annuity' => 'global_reports#annuity'
    post '/global_reports/certificate_documents' => 'global_reports#certificate_documents'
    get '/group_reports/products' => 'group_reports#products'
  end

  resources :document_approvment, only: [:index, :create]
  resources :dac_approvment, only: [:index, :create]
  resources :pending_documents, only: [:index]

  resource :records, only: [:show] do
    resources :documents, module: :records
    resources :logs, only: [:index], module: :records
    resources :unity_suspension_types, except: [:delete], module: :records
    resources :group_types, except: [:delete], module: :records
    resources :product_categories, except: [:delete], module: :records
    resources :products, except: [:delete], module: :records
    resources :scopes, module: :records
    resources :acronyms, module: :records
    resources :suspension_types, module: :records
  end

  resources :groups, except: :delete do
    resources :change_core, module: :groups, only: [:new, :create]
    resources :send_documents, module: :groups
    resources :dac_documents, module: :groups

    get "/outdateds" => "groups#outdateds"
    post "/update_outdateds" => "groups#update_outdateds"
    get "/group_dacs" => "groups#group_dacs"
    post "/group_dacs" => "groups#create_group_dacs"
    resources :certificate_groups, module: :groups do
      resources :certificate, only: [:index, :show]
    end
    resources :production_unities, module: :groups do
      get 'certificates'
      resources :send_documents, module: :production_unities
      post 'remove_suspension' => 'production_unities#remove_suspension'
      post 'set_updated' => 'production_unities#set_updated'
      resources :production_unity_farmers do
        post "" => "production_unity_farmers#change_responsible"
      end
      resources :production_unity_scopes do
        resources :scope_products, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :unity_suspensions
    end
    resources :set_suplentes, except: [:delete, :edit, :update], module: :groups
    resources :farmers, except: :delete do
      post 'set_updated' => 'farmers#set_updated'

      collection do
        get 'validate_name'
      end
      
      get 'certificates'
      resources :farmer_group_changes, module: :farmers
      resources :dacs, except: [:update, :edit], module: :farmers
      resources :daps, except: [:update, :edit], module: :farmers
      resources :farmer_families, module: :farmers
      resources :send_documents, module: :farmers
      resources :farmer_suspensions, module: :farmers
        post 'remove_suspension' => 'farmers#remove_suspension'
    end
  end

  resources :cores, except: [:delete] do
    resources :core_coordinators, except: [:show, :destroy], module: :cores do
      member do
        patch :update_current
      end
    end
    resources :payments, module: :cores
  end

  resources :system_settings, only: [:index, :edit, :update]

  resources :admin_password_updater

  root 'home#index'

end

app/controllers/excluded_data/farmers_controller.rb
class ExcludedData::FarmersController < ApplicationController
  before_action :require_admin

  def index
    @q  = Farmer.unscoped.order(name: :asc).where(excluded: true).ransack(params[:q])
    @count = @q.result.count
    @farmers = @q.result.page(params[:page]).per(25)
  end
end

app/controllers/farmers/dacs_controller.rb
class Farmers::DacsController < ApplicationController
  before_action :set_dac, only: [:show, :edit, :update, :destroy]
  before_action :set_group
  before_action :set_farmer
  before_action :require_admin, only: [:new, :create, :destroy]
  before_action :require_normal_core, only: [:show, :index]

  # GET /dacs
  # GET /dacs.json
  def index
    @dacs = @farmer.dacs.page(params[:page]).per(20)
  end

  # GET /dacs/1
  # GET /dacs/1.json
  def show
  end

  # GET /dacs/new
  def new
    @dac = @farmer.dacs.build
  end


  # POST /dacs
  # POST /dacs.json
  def create
    @dac = @farmer.dacs.build(dac_params)
    @dac.added_by = name_and_type_of_logged_user
    respond_to do |format|
      if @dac.save
        SystemLog.create(description: "Cadastraou uma nova D.A.C para o agricultor #{@farmer.name}(#{@farmer.farmer_code})", author: name_and_type_of_logged_user)
        format.html { redirect_to [@farmer.group, @farmer, @dac], notice: 'D.A.C criado com sucesso.' }
        format.json { render :show, status: :created, location: @dac }
      else
        format.html { render :new }
        format.json { render json: @dac.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /dacs/1
  # DELETE /dacs/1.json
  def destroy
    @dac.destroy
    SystemLog.create(description: "Deletou uma D.A.C do agricultor #{@farmer.name}(#{@farmer.farmer_code})", author: name_and_type_of_logged_user)
    respond_to do |format|
      format.html { redirect_to group_farmer_dacs_url(@farmer.group, @farmer), notice: 'D.A.C Deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dac
      @dac = Dac.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_farmer
      @farmer = @group.farmers.find(params[:farmer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dac_params
      params.require(:dac).permit(:dac_date, :sampling)
    end
end

app/controllers/farmers/daps_controller.rb
class Farmers::DapsController < ApplicationController
  before_action :set_dap, only: [:show, :edit, :update, :destroy]
  before_action :set_group
  before_action :set_farmer
  before_action only: [:new, :create, :destroy] do
    #Necessita ser dono,
    require_current_or_admin(@farmer.group.core.id, false, false)

  end
  before_action :require_normal_core, only: [:show, :index]
  # GET /daps
  # GET /daps.json
  def index
    @daps = @farmer.daps.page(params[:page]).per(20)
  end

  # GET /daps/1
  # GET /daps/1.json
  def show
  end

  # GET /daps/new
  def new
    @dap = @farmer.daps.build
  end


  # POST /daps
  # POST /daps.json
  def create
    @dap = @farmer.daps.build(dap_params)
    @dap.added_by = name_and_type_of_logged_user
    respond_to do |format|
      if @dap.save
        SystemLog.create(description: "Cadastraou uma nova D.A.P para o agricultor #{@farmer.name}(#{@farmer.farmer_code}) com o numero #{@dap.dap_number}", author: name_and_type_of_logged_user)
        format.html { redirect_to [@farmer.group, @farmer, @dap], notice: 'D.A.P criado com sucesso.' }
        format.json { render :show, status: :created, location: @dap }
      else
        format.html { render :new }
        format.json { render json: @dap.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /daps/1
  # DELETE /daps/1.json
  def destroy
    @dap.destroy
    SystemLog.create(description: "Deletou um DAP do agricultor #{@farmer.name}(#{@farmer.farmer_code}) com o numero #{@dap.dap_number}", author: name_and_type_of_logged_user)
    respond_to do |format|
      format.html { redirect_to group_farmer_daps_url(@farmer.group, @farmer), notice: 'D.A.P Deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dap
    @dap = Dap.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_farmer
    @farmer = @group.farmers.find(params[:farmer_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dap_params
    params.require(:dap).permit(:dap_number, :validity, :emission_date)
  end
end

app/controllers/farmers/farmer_families_controller.rb
class Farmers::FarmerFamiliesController < ApplicationController
  before_action :set_farmer_family, only: [:show, :edit, :update, :destroy]
  before_action :set_farmer
  before_action :set_group

  before_action :require_normal_core
  before_action only: [:new, :edit, :create, :update, :destroy] do
    require_current_or_admin(@group.core.id)
  end


  # GET /farmer_families
  # GET /farmer_families.json
  def index
    @farmer_families = @farmer.farmer_families
  end

  # GET /farmer_families/1
  # GET /farmer_families/1.json
  def show
  end

  # GET /farmer_families/new
  def new
    @farmer_family = @farmer.farmer_families.build
  end

  # GET /farmer_families/1/edit
  def edit
  end

  # POST /farmer_families
  # POST /farmer_families.json
  def create
    @farmer_family = @farmer.farmer_families.build(farmer_family_params)

    respond_to do |format|
      if @farmer_family.save
        SystemLog.create(description: "Cadastraou uma novo membro da família para o agricultor #{@farmer.name}(#{@farmer.farmer_code}) chamado #{@farmer_family.name}", author: name_and_type_of_logged_user)
        format.html { redirect_to [@group, @farmer_family.farmer, @farmer_family], notice: 'Integrante da familia adicionado com sucesso' }
        format.json { render :show, status: :created, location: @farmer_family }
      else
        format.html { render :new }
        format.json { render json: @farmer_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farmer_families/1
  # PATCH/PUT /farmer_families/1.json
  def update
    respond_to do |format|
      if @farmer_family.update(farmer_family_params)
        SystemLog.create(description: "Atualizou as informações do membro da família do agricultor #{@farmer.name}(#{@farmer.farmer_code}) chamado #{@farmer_family.name}", author: name_and_type_of_logged_user)
        format.html { redirect_to [@group, @farmer_family.farmer, @farmer_family], notice: 'Integrante da familia atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @farmer_family }
      else
        format.html { render :edit }
        format.json { render json: @farmer_family.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
   if @farmer_family.destroy
    SystemLog.create(description: "deletou um membro da família do agricultor #{@farmer.name}(#{@farmer.farmer_code}) chamado #{@farmer_family.name}", author: name_and_type_of_logged_user)
    redirect_to group_farmer_farmer_families_url(@group, @farmer), notice: "Membro da fámilia removido com sucesso"
   else
    redirect_to [@group, @farmer, @farmer_family], alert: "Não foi possível deletar o membro da fámilia"
   end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farmer_family
      @farmer_family = FarmerFamily.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_farmer
      @farmer = Farmer.find(params[:farmer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farmer_family_params
      params.require(:farmer_family).permit(:name, :cpf, :farmer_id, :gender, :birthday)
    end


end

app/controllers/farmers/farmer_group_changes_controller.rb
class Farmers::FarmerGroupChangesController < ApplicationController

  before_action do
    set_group
    set_farmer
    require_current_or_admin(@group.core.id, false, false)
  end

  # GET /farmer_group_changes
  # GET /farmer_group_changes.json
  def index
    @farmer_group_changes = @farmer.farmer_group_changes.all.page(params[:page]).per(20)
  end


  # GET /farmer_group_changes/new
  def new
    @farmer_group_change = @farmer.farmer_group_changes.build
  end


  # POST /farmer_group_changes
  # POST /farmer_group_changes.json
  def create
    @farmer_group_change = @farmer.farmer_group_changes.build(farmer_group_change_params)

    respond_to do |format|
      if @farmer_group_change.save
        SystemLog.create(description: "Trocou o agricultor #{@farmer_group_change.farmer.name} para o grupo #{@farmer_group_change.group.name}", author: name_and_type_of_logged_user)
        format.html { redirect_to [@farmer_group_change.group, @farmer_group_change.farmer], notice: 'Agricultor agora pertence há um novo grupo !.' }
        format.json { render :show, status: :created, location: @farmer_group_change }
      else
        format.html { render :new }
        format.json { render json: @farmer_group_change.errors, status: :unprocessable_entity }
      end
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_farmer
    @farmer = @group.farmers.find(params[:farmer_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def farmer_group_change_params
    params.require(:farmer_group_change).permit(:farmer_id, :group_id)
  end
end

app/controllers/farmers/farmer_suspensions_controller.rb
class Farmers::FarmerSuspensionsController < ApplicationController

  before_action do
    set_group
    require_current_or_admin(@group.core.id)
    set_farmer
  end
  before_action only: [:new, :create] do
    require_admin
    if @farmer.is_suspended?
      redirect_to [@group, @farmer], alert: "Impossível suspender quem já está suspenso."
    end
  end
  before_action only: [:edit, :update] do
    require_admin
  end
  before_action :set_farmer_suspension, only: [:show, :edit, :update, :destroy]

  # GET /farmer_suspensions
  # GET /farmer_suspensions.json
  def index
    @farmer_suspensions = @farmer.farmer_suspensions.page(params[:page]).per(20)
  end



  # GET /farmer_suspensions/1
  # GET /farmer_suspensions/1.json
  def show
  end

  # GET /farmer_suspensions/new
  def new
    @farmer_suspension = @farmer.farmer_suspensions.build
  end

  # GET /farmer_suspensions/1/edit
  def edit
  end

  # POST /farmer_suspensions
  # POST /farmer_suspensions.json
  def create
    @farmer_suspension = @farmer.farmer_suspensions.build(farmer_suspension_params)

    respond_to do |format|
      if @farmer_suspension.save
        @farmer_suspension.update_suspension_reasons(params[:suspension_types])
        @farmer_suspension.create_sig_org_status
        SystemLog.create(description: "Suspendeu #{@farmer.name}(#{@farmer.farmer_code}", author: name_and_type_of_logged_user)
        format.html { redirect_to [@group, @farmer], notice: "#{@farmer.name} foi suspenso com sucesso." }
        format.json { render :show, status: :created, location: @farmer_suspension }
      else
        format.html { render :new }
        format.json { render json: @farmer_suspension.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farmer_suspensions/1
  # PATCH/PUT /farmer_suspensions/1.json
  def update
    respond_to do |format|
      if @farmer_suspension.update(farmer_suspension_params)
        @farmer_suspension.update_suspension_reasons(params[:suspension_types])
        @farmer_suspension.create_sig_org_status(true) #é update, então, true
        SystemLog.create(description: "Atualizou as informações da suspensão de #{@farmer.name}(#{@farmer.farmer_code} da data: #{@farmer_suspension.suspension_date.strftime("%d/%m/%Y")
}", author: name_and_type_of_logged_user)
        format.html { redirect_to [@group, @farmer, @farmer_suspension], notice: "Suspensão de #{@farmer.name} foi atualizada com sucesso" }
        format.json { render :show, status: :ok, location: @farmer_suspension }
      else
        format.html { render :edit }
        format.json { render json: @farmer_suspension.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_farmer
      @farmer = @group.farmers.find(params[:farmer_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_farmer_suspension
      @farmer_suspension = @farmer.farmer_suspensions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farmer_suspension_params
      params.require(:farmer_suspension).permit(:description, :suspension_date)
    end
end

app/helpers/farmer_families_helper.rb
module FarmerFamiliesHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/views/farmers/farmer_families/_form.html.erb
<%= simple_form_for([@group, @farmer, @farmer_family]) do |f| %>
  <%= show_errors(@farmer_family) %>

  <div class="row">
    <div class="col-md-3">
      <%= f.input :name %>

      <%= f.input :cpf %>

      <%= f.input :gender, collection: Genders.to_a, include_blank: false %>

      <%= f.input :birthday, as: :date_picker, input_html: {value: f.object.birthday.try(:strftime, '%d/%m/%Y')} %>

      <%= f.submit t "modules.farmer_families.new_when_#{@farmer.number_type}", data: {"disable-with" => "Salvando..."} %>
    </div>
  </div>


<% end %>

app/views/farmers/farmer_families/edit.html.erb
<%= link_to 'Pagina ínicial', root_path %> -<%= link_to " #{@group.core.name} -", @group.core if user_type == 4 %> <%= link_to 'Listando grupos', groups_path %> - <%= link_to "Grupo: #{@group.name}", @group %> - <%= link_to 'Agricultores', group_farmers_path %> - <%= link_to @farmer.name, [@group, @farmer] %> - <%= link_to "Listando membros da familia", group_farmer_farmer_families_path %> - Editando <%= @farmer_family.name %>

<h1>Editando membro da família</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [@group, @farmer, @farmer_family] %> |
<%= link_to 'Voltar', group_farmer_farmer_families_path %>

app/views/farmers/farmer_families/index.html.erb
<%= link_to 'Pagina ínicial', root_path %> -<%= link_to " #{@group.core.name} -", @group.core if user_type == 4 %> <%= link_to 'Listando grupos', groups_path %> - <%= link_to "Grupo: #{@group.name}", @group %> - <%= link_to 'Agricultores', group_farmers_path %> - <%= link_to @farmer.name, [@group, @farmer] %> - Listando membros da familia

<% if @farmer_families.count != 0 %>
<h1><%= t "modules.farmer_families.index_when_#{@farmer.number_type}" %></h1>

<table class = "table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @farmer_families.each do |farmer_family| %>
      <tr>
        <td><%= farmer_family.name %></td>
        <td><%= farmer_family.cpf %></td>
        <td><%= link_to 'Mostrar', group_farmer_farmer_family_path(@group,@farmer,farmer_family) %></td>
        <td><%= link_to 'Editar', edit_group_farmer_farmer_family_path(@group,@farmer,farmer_family) if require_current_or_admin(@group.core.id, true)%></td>
        <td><%= link_to "Deletar", [@group, @farmer, farmer_family], method: :delete, data: {confirm: "Você tem certeza que deseja deletar o agricultor?"} if require_current_or_admin(@group.core.id, true)%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% else %>
  <h1><%= t "modules.farmer_families.without_when_#{@farmer.number_type}" %></h1>
<% end %>

<% if user_type == 4 or current_user == @group.core.id #Se for adm ou o nucleo dono. %>
<%= link_to t("modules.farmer_families.new_when_#{@farmer.number_type}"), new_group_farmer_farmer_family_path, class: 'btn btn-default' %>
<% end %>

app/views/farmers/farmer_families/new.html.erb
<%= link_to 'Pagina ínicial', root_path %> -<%= link_to " #{@group.core.name} -", @group.core if user_type == 4 %> <%= link_to 'Listando grupos', groups_path %> - <%= link_to "Grupo: #{@group.name}", @group %> - <%= link_to 'Agricultores', group_farmers_path %> - <%= link_to @farmer.name, [@group, @farmer] %> - <%= link_to "Listando membros da familia", group_farmer_farmer_families_path %> - Novo
<h1><%= t "modules.farmer_families.new_when_#{@farmer.number_type}" %></h1>


<%= render 'form' %>

<%= link_to 'Voltar', group_farmer_farmer_families_path %>

app/views/farmers/farmer_families/show.html.erb
<%= link_to 'Pagina ínicial', root_path %> -<%= link_to " #{@group.core.name} -", @group.core if user_type == 4 %> <%= link_to 'Listando grupos', groups_path %> - <%= link_to "Grupo: #{@group.name}", @group %> - <%= link_to 'Agricultores', group_farmers_path %> - <%= link_to @farmer.name, [@group, @farmer] %> - <%= link_to "Listando membros da familia", group_farmer_farmer_families_path %> - <%= @farmer_family.name %>

<p>
  <strong>Nome:</strong>
  <%= @farmer_family.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @farmer_family.cpf %>
</p>

<p>
  <strong>Gênero:</strong>
  <%= @farmer_family.gender.present? ? @farmer_family.gender_humanize : 'Não informado' %>
</p>
<% if @farmer_family.birthday %>
  <p>
    <strong>Data de nascimento:</strong>
    <%= l @farmer_family.birthday %>
  </p>

<% end %>

<%= link_to 'Editar', edit_group_farmer_farmer_family_path(@group, @farmer, @farmer_family) if require_current_or_admin(@group.core.id, true) %> |
<%= link_to 'Voltar', group_farmer_farmer_families_path %>