config/routes.rb
Rails.application.routes.draw do
  resource :excluded_data, only: [:show] do
    resources :farmers, only: [:index], module: :excluded_data
    resources :production_unities, only: [:index], module: :excluded_data
    resources :groups, only: [:index], module: :excluded_data
  end

  # Help
  get '/help/reduce_pdf_size'

  get 'document_access_visualizations/core'

  get 'document_access_visualizations/group'

  get 'document_access_visualizations/documents_farmers_and_production_unities'

  get 'document_access_visualizations/farmer'

  get 'document_access_visualizations/production_unity'

  get 'document_access_visualizations/certificate'

  resources :document_visualizations
  get "/home/search" => "home#search"
  get "/home/report" => "home#report"
  resource :user_sessions
  resource :document_visualization_sessions

  namespace :view_reports do
    get '/view_reports' => 'view_reports#index'
    get '/farmer_reports' => 'farmer_reports#index'
    get '/product_reports' => 'product_reports#index'
    get '/city_reports' => 'city_reports#index'
    get '/production_unity_reports' => 'production_unity_reports#index'
  end

  namespace :reports do
    get 'index'
    get 'quantity'
    get 'annuity'
    get 'certified_members'

    get '/core_reports/actual_situation' => 'core_reports#actual_situation'
    get '/core_reports/products' => 'core_reports#products'
    get '/global_reports/actual_situation' => 'global_reports#actual_situation'
    get '/global_reports/annuity' => 'global_reports#annuity'
    post '/global_reports/certificate_documents' => 'global_reports#certificate_documents'
    get '/group_reports/products' => 'group_reports#products'
  end

  resources :document_approvment, only: [:index, :create]
  resources :dac_approvment, only: [:index, :create]
  resources :pending_documents, only: [:index]

  resource :records, only: [:show] do
    resources :documents, module: :records
    resources :logs, only: [:index], module: :records
    resources :unity_suspension_types, except: [:delete], module: :records
    resources :group_types, except: [:delete], module: :records
    resources :product_categories, except: [:delete], module: :records
    resources :products, except: [:delete], module: :records
    resources :scopes, module: :records
    resources :acronyms, module: :records
    resources :suspension_types, module: :records
  end

  resources :groups, except: :delete do
    resources :change_core, module: :groups, only: [:new, :create]
    resources :send_documents, module: :groups
    resources :dac_documents, module: :groups

    get "/outdateds" => "groups#outdateds"
    post "/update_outdateds" => "groups#update_outdateds"
    get "/group_dacs" => "groups#group_dacs"
    post "/group_dacs" => "groups#create_group_dacs"
    resources :certificate_groups, module: :groups do
      resources :certificate, only: [:index, :show]
    end
    resources :production_unities, module: :groups do
      get 'certificates'
      resources :send_documents, module: :production_unities
      post 'remove_suspension' => 'production_unities#remove_suspension'
      post 'set_updated' => 'production_unities#set_updated'
      resources :production_unity_farmers do
        post "" => "production_unity_farmers#change_responsible"
      end
      resources :production_unity_scopes do
        resources :scope_products, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :unity_suspensions
    end
    resources :set_suplentes, except: [:delete, :edit, :update], module: :groups
    resources :farmers, except: :delete do
      post 'set_updated' => 'farmers#set_updated'

      collection do
        get 'validate_name'
      end
      
      get 'certificates'
      resources :farmer_group_changes, module: :farmers
      resources :dacs, except: [:update, :edit], module: :farmers
      resources :daps, except: [:update, :edit], module: :farmers
      resources :farmer_families, module: :farmers
      resources :send_documents, module: :farmers
      resources :farmer_suspensions, module: :farmers
        post 'remove_suspension' => 'farmers#remove_suspension'
    end
  end

  resources :cores, except: [:delete] do
    resources :core_coordinators, except: [:show, :destroy], module: :cores do
      member do
        patch :update_current
      end
    end
    resources :payments, module: :cores
  end

  resources :system_settings, only: [:index, :edit, :update]

  resources :admin_password_updater

  root 'home#index'

end

app/models/group_type.rb
# == Schema Information
#
# Table name: group_types
#
#  id          :integer          not null, primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class GroupType < ActiveRecord::Base
  has_many :groups
  validates_uniqueness_of :description
  validates_presence_of(:description)
end

app/controllers/excluded_data/groups_controller.rb
class ExcludedData::GroupsController < ApplicationController
  before_action :require_admin

  def index
    @q  = Group.unscoped.order(name: :asc).where(excluded: true).ransack(params[:q])
    @count = @q.result.count
    @groups = @q.result.page(params[:page]).per(25)
  end
end

app/controllers/groups/certificate_controller.rb
class Groups::CertificateController < ApplicationController
  before_action :set_group
  before_action :set_certificate_group
  before_action :set_certificate, only: [:show]
  before_action do
    require_current_or_admin(@group.core.id)
  end

  def index
    @certificates = @certificate_group.certificates
    respond_to do |format|
       format.pdf {
         render pdf: "relatorio", orientation: "landscape", encoding: "utf-8", margin: {top: 0, bottom: 0, left: 0, right: '0'}
       }
    end
  end

  def show
    respond_to do |format|
       format.pdf {
         render pdf: "relatorio", orientation: "landscape", encoding: "utf-8", margin: {top: 0, bottom: 0, left: 0, right: '0'}
       }
    end
  end

  private

  def set_group
    @group = Group.unscoped.find(params[:group_id])
  end

  def set_certificate_group
    @certificate_group = @group.certificate_groups.find(params[:certificate_group_id])
  end

  def set_certificate
    @certificate = @certificate_group.certificates.find(params[:id])
  end
end

app/controllers/groups/certificate_groups_controller.rb
class Groups::CertificateGroupsController < ApplicationController
  before_action :set_group
  before_action :set_certificate_group, only: [:show, :edit]
  before_action do
    require_current_or_admin(@group.core.id)
    redirect_to root_path, notice: 'Área restrita' unless can_generate_certificate?
  end

  # GET /certificate_groups
  # GET /certificate_groups.json
  def index
    @certificate_groups = @group.certificate_groups.order(created_at: :desc).page(params[:page]).per(20)
  end

  # GET /certificate_groups/1
  # GET /certificate_groups/1.json
  def show
  end

  # GET /certificate_groups/new
  def new
    @group_analysis = Certification.verify_and_list(@group)
    @certificate_group = @group.certificate_groups.build
  end

  # GET /certificate_groups/1/edit
  def edit
  end

  # POST /certificate_groups
  # POST /certificate_groups.json
  def create
    @group_analysis = Certification.verify_and_list(@group)
    @certificate_group = @group.certificate_groups.build(certificate_group_params)
    @certificate_group.farmers = params[:farmers].present? ? params[:farmers] : []
    @certificate_group.agribusiness = params[:agribusiness].present? ? params[:agribusiness] : []
    respond_to do |format|
      if @certificate_group.save
        SystemLog.create(description: "Gerou certificados para o grupo #{@group.name}", author: name_and_type_of_logged_user)

        format.html { redirect_to [@group, @certificate_group], notice: 'Certificados do grupo criado com sucesso.' }
        format.json { render :show, status: :created, location: @certificate_group }
      else
        format.html { render :new }
        format.json { render json: @certificate_group.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  
  def set_group
    @group = Group.find(params[:group_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_certificate_group
    @certificate_group = CertificateGroup.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def certificate_group_params
    params.require(:certificate_group).permit(:meeting_number, :meeting_page, :meeting_date, :group_id, :city_id)
  end
end

app/controllers/groups/change_core_controller.rb
class Groups::ChangeCoreController < ApplicationController
  before_action :set_group

  before_action do
    require_admin
  end

  def new; end

  def create
    core = Core.find(params[:group][:core_id])
    success = GroupService.new(@group).change_to_core(core)

    if success
      SystemLog.create(description: "Alterou #{@group.name} para o núcleo #{core.name}", author: name_and_type_of_logged_user)
      redirect_to [@group], notice: 'Núcleo alterado com sucesso'
    elsif true
      render :new, alert: 'Não foi possível alterar o núcleo'
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups/dac_documents_controller.rb
class Groups::DacDocumentsController < ApplicationController
  before_action :set_group, only: [:create]
  respond_to :js, :html, :json

  def create
    response = DacDocumentation::Create.execute(dac_document_params, current_user_instance)

    if response && response.valid?
      SystemLog.create(description: "Enviou um DAC para #{@group.name}", author: name_and_type_of_logged_user)
      
      render nothing: true, status: 200
    else
      render nothing: true, status: 400
    end
  end

  private

  def dac_document_params
    params.require(:dac_document).permit(:id, :file, :observations, :dac_date)
                                 .merge(status: :pending, group_id: @group.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups/production_unities/send_documents_controller.rb
class Groups::ProductionUnities::SendDocumentsController < ApplicationController
  before_action :set_group, only: [:index, :create]
  respond_to :js, :html, :json

  def index
    subject = @production_unity.is_agribusiness? ? 'agribusiness' : 'production_unity'
    @documents = Document.where(status: :active, subject: subject)

    @sended_documents = DocumentSended.where(subject: @production_unity)
  end

  def create
    response = DocumentApprovement::Create.execute(document_params.merge(subject: @production_unity), current_user_instance)

    if response && response.valid?
      SystemLog.create(description: "Enviou documento para #{@production_unity.name}",
                       author: name_and_type_of_logged_user)
      render nothing: true, status: 200
    else
      render nothing: true, status: 400
    end
  end

  private

  def document_params
    params.require(:document_sended).permit(:file, :url, :document_id, :observations).merge(status: :pending)
  end

  def set_group
    @production_unity = ProductionUnity.find(params[:production_unity_id])
    @group = @production_unity.group
  end
end

app/controllers/groups/production_unities_controller.rb
# coding: utf-8
class Groups::ProductionUnitiesController < ApplicationController
  before_action :set_user
  before_action do
    require_current_or_admin(@group.core.id)
  end

  def index
    @production_unities = @group.production_unities.all.order(name: :asc).page(params[:page]).per(20)
  end

  def show
    @production_unity = @group.production_unities.find(params[:id])
    @last_certificate = @production_unity.certificate_names.joins(certificate: [:certificate_group])
                                                           .where(name_type: 3)
                                                           .order('certificate_groups.meeting_date')
                                                           .last
  end

  def certificates
    @production_unity = @group.production_unities.find(params[:production_unity_id])
    @certificates = @production_unity.certificate_names.where(name_type: 3).page(params[:page]).per(20)
  end

  def remove_suspension
    @production_unity = @group.production_unities.find(params[:production_unity_id])
    if @production_unity.is_suspended?
      @unity_suspension = @production_unity.unity_suspensions.build(suspension_date: Date.today, suspension_type: 'Remoção da suspensão')
      @unity_suspension.save
      @unity_suspension.create_sig_org_status
      SystemLog.create(description: "Removeu a suspensão de uma unidade de produção ou agroindustria do grupo #{@group.name} chamada #{@production_unity.name}", author: name_and_type_of_logged_user)

      redirect_to [@group, @production_unity], notice: "Suspensão removida com sucesso."
    else
      redirect_to [@group, @production_unity], notice: "Está unidade não está suspensa."
    end
  end

  def set_updated
    @production_unity = ProductionUnity.find(params[:production_unity_id])
    require_current_or_admin(@production_unity.group.core.id, false, true)
    if @production_unity.sig_org_status == "Atualizado"
      redirect_to [@production_unity.group, @production_unity], alert: "Está propriedade já está atualizado"
    else
      @production_unity.set_sig_org_updated
      SystemLog.create(description: "Atualizou #{@production_unity.name} do grupo #{@production_unity.group.name} no SigOrg.", author: name_and_type_of_logged_user)
      redirect_to [@production_unity.group, @production_unity], notice: "Agora #{@production_unity.name} está atualizado no SIG.ORG"
    end
  end

  def new

    @production_unity_form = ProductionUnityForm.new
    @production_unity_form.lat_type = "S"
    @production_unity_form.lon_type = "O"
    if params[:farmer_id].present?
      farmer = @group.farmers.find(params[:farmer_id])
      @production_unity_form.farmer_id = farmer.id
      @production_unity_form.address = farmer.address
      @production_unity_form.city_id = farmer.city_id
      @production_unity_form.neighborhood = farmer.neighborhood
    end
  end

  def edit
    @production_unity = @group.production_unities.find(params[:id])
  end

  def create
    scope_type = params[:production_unity_form].permit(:scope_type).first[1]
    production_params = scope_type == "1" ? production_unity_form_params : agribusiness_form_params
    @production_unity_form = ProductionUnityForm.new(production_params)
    @production_unity_form.group_id = @group.id
    @production_unity_form.scopes = params.require(:scopes) if not params[:scopes].nil?

    if @production_unity_form.save!
      SystemLog.create(description: "Criou uma unidade de produção ou agroindustria para o grupo #{@group.name} chamada #{@production_unity_form.name}", author: name_and_type_of_logged_user)
      redirect_to(group_production_unity_path(@group, @production_unity_form.production_unity_to_read), notice: "Unidade de produção criada com sucesso.")
    else
      render :new
    end
  end

  def update
    @production_unity = @group.production_unities.find(params[:id])
    production_params = @production_unity.scope_type == 1 ? edit_production_unity_params : edit_agribusiness_params
    if @production_unity.update(production_params)
      SystemLog.create(description: "Atualizou as informações básicas de uma unidade de produção ou agroindustria para o grupo #{@group.name} chamada #{@production_unity.name}", author: name_and_type_of_logged_user)
      redirect_to [@group, @production_unity], notice: "Edições realizadas com sucesso."
    else
      render :edit
    end

  end

  def destroy
    @production_unity = @group.production_unities.find(params[:id])
    @production_unity.excluded = true
    @production_unity.save(validate: false)

    SystemLog.create(description: "Excluiu uma propriedade do #{@group.name} chamada #{@production_unity.name}", author: name_and_type_of_logged_user)

    redirect_to group_path(@group), notice: 'Propriedade foi excluída com sucesso'
  end

  private

  def set_user
    @group = Group.find(params[:group_id])
  end

  def edit_production_unity_params
    params.require(:production_unity).permit(:lat_hour, :lat_minute, :lat_second, :lat_type, :lon_hour, :lon_minute, :lon_second, :lon_type, :cep, :name, :production_type, :address, :neighborhood, :city_id, :geographic_coordinates, :total_area, :total_organic_area, :total_native_area)
  end

  def edit_agribusiness_params

    params.require(:production_unity).permit(:register_type, :cep, :name, :production_type, :address, :neighborhood, :city_id, :fantasy_name, :number_type, :number_type, :register_number, :register_number, :phone, :email, :number)

  end

  def production_unity_form_params
    params.require(:production_unity_form).permit(
      :name, :address, :neighborhood, :city_id, :cep, :group_id, :farmer_id, :scope_type, :geographic_coordinates, :total_area, :total_native_area, :total_organic_area, :production_type,
      :lat_hour, :lat_minute, :lat_second, :lat_type, :lon_hour, :lon_minute, :lon_second, :lon_type)
  end

  def agribusiness_form_params
    params.require(:production_unity_form).permit(
      :name, :number, :number_type, :fantasy_name, :cep, :register_type, :register_number,
      :address, :neighborhood, :city_id, :group_id, :farmer_id, :scope_type, :production_type, :phone, :email)
  end

end

app/helpers/groups/certificate_helper.rb
module Groups::CertificateHelper
  # def pluralize_without_count(count, if_one, if_more)
  #   if count != 0
  #     count == 1 ? "#{if_one}" : "#{if_more}"
  #   end
  # end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/production_unity_scopes/_agribusiness_form.html.erb
<%= bootstrap_form_for([@group, @production_unity, @production_unity_scope]) do |f| %>
  <%= f.select :scope_id, Scope.where(scope_type: 2).collect {|c| [c.name, c.id]}, label: "Escopo" %>
  <%= f.submit "Adicionar escopo",  data: {"disable-with" => "Salvando..."} %>
<% end %>

app/views/groups/production_unity_scopes/_agribusiness_show.html.erb
<h2><%= @production_unity_scope.scope.name %> de <%= @production_unity.name %>

<div class = "row">
  <br>
  <div class = "col-md-6">
    <div class = "panel panel-default">
      <div class = "panel-heading">
        <h3 class = "panel-title">Informações</h3>
      </div>
      <div class = "panel-body">
        <p>
          <strong>Sigla:</strong> <%= @production_unity_scope.scope.acronym %><br>
        </p>
        <p>
          <strong>Quantidade de produtos:</strong> <%= @production_unity_scope.scope_products.count %><br>
        </p>
      </div>

    </div>
  </div>
  <div class = "col-md-6">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h3 class = "panel-title">Ações</h3>
      </div>
      <%= link_to 'Adicionar produto', new_group_production_unity_production_unity_scope_scope_product_path(@group, @production_unity, @production_unity_scope), class: "list-group-item" %>

    </div>
  </div>
</div>

<% if @production_unity_scope.scope_products.count != 0 %>
<h3>Produtos de <%= @production_unity.name %> no escopo <%= @production_unity_scope.scope.name %></h3>
<table class = "table">
  <tr>
    <th>Produto</th>
    <th>Tamanho da embalagem</th>
    <th>Volume por ano</th>
    <th>Com ingredientes orgânicos?</th>
    <th>Data da ultima modificação</th>
    <th colspan="2">Ações</th>
  </tr>
  <% @production_unity_scope.scope_products.joins(:product).order('products.name').each do |scope_product| %>
    <tr>
      <td><%= scope_product.product.name %></td>
      <td>
      <% if scope_product.package_size.present? %><%= scope_product.package_size %> <%= ScopeProduct::UNITIES[scope_product.package_size_unity] %>(s)
      <% else %>
        Não informado
      <% end %></td>
      <td>
      <% if scope_product.amount_per_year.present? %>
      <%= rounded_formated_value(scope_product.amount_per_year) %> <%= ScopeProduct::UNITIES[scope_product.amount_per_year_unity] %>(s)
      <% else %>
        Não informado
      <% end %>
      </td>
      <td><%= scope_product.is_processor ? "Sim" : "Não" %></td>
      <td><%= l(scope_product.updated_at) %></td>
      <td><%= link_to "Editar", edit_group_production_unity_production_unity_scope_scope_product_path(@group, @production_unity, @production_unity_scope, scope_product), class: "btn btn-default btn-sm" %></td>
      <td><%= link_to "Remover", [@group, @production_unity, @production_unity_scope, scope_product], method: :delete, class: "btn btn-danger btn-sm" %>
    </tr>
  <% end %>
</table>
<% else %>
  <h3 class = "alert alert-warning">Não há produtos vinculados a este escopo ainda !  Por favor, adicione no menu ações no canto superior direito </h3>
<% end %>

app/views/groups/production_unity_scopes/_production_unity_form.html.erb
<%= bootstrap_form_for([@group, @production_unity, @production_unity_scope]) do |f| %>
  <% if @production_unity_scope.id.nil? %>
	  <%= f.select :scope_id, Scope.where(scope_type: 1).collect {|c| [c.name, c.id]}, label: "Escopo" %>
  <% end %>
  <%= f.number_field :total_area, label: "Àrea total (Deixe em branco para calcular automaticamente)" %>

  <%= f.submit "Adicionar escopo",  data: {"disable-with" => "Salvando..."} %>
<% end %>

app/views/groups/production_unity_scopes/_production_unity_show.html.erb
<h2><%= @production_unity_scope.scope.name %> de <%= @production_unity.name %>

<div class = "row">
  <div class = "col-md-6">
    <div class = "panel panel-default">
      <div class = "panel-heading">
        <h3 class = "panel-title">Informações</h3>
      </div>
      <div class = "panel-body">
        <p>
          <strong>Sigla:</strong> <%= @production_unity_scope.scope.acronym %><br>
        </p>
        <p>
          <strong>Área total:</strong>
          <% if @production_unity_scope.total_area.present? %>
            <%= rounded_formated_value(@production_unity_scope.total_area) %> ha (Valor fornecido manualmente)
          <% else %>
            <%= rounded_formated_value(@production_unity.scope_products.where.not(area: nil).map(&:area).sum) %>ha<%= " - Não foi fornecida a área de #{@production_unity.scope_products.where(area: nil).count} produto(s)." if @production_unity.scope_products.where(area: nil).any? %>
          <% end %>
        </p>

        <p>
          <strong>Quantidade de produtos:</strong> <%= @production_unity_scope.scope_products.count %><br>
        </p>
        <%= link_to 'Editar Informações', edit_group_production_unity_production_unity_scope_path(@group, @production_unity, @production_unity_scope), class: 'btn btn-default' %>
      </div>

    </div>
  </div>
  <div class = "col-md-6">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h3 class = "panel-title">Ações</h3>
      </div>
      <%= link_to 'Adicionar produto', new_group_production_unity_production_unity_scope_scope_product_path(@group, @production_unity, @production_unity_scope), class: "list-group-item" %>

    </div>
  </div>
</div>

<% if @production_unity_scope.scope_products.count != 0 %>
<h3>Produtos de <%= @production_unity.name %> no escopo <%= @production_unity_scope.scope.name %></h3>
<table class = "table">
  <tr>
    <th>Produto</th>
    <th>Quantidade</th>
    <th>Area (ha)</th>
    <th>Data da ultima modificação</th>
    <th colspan="2">Ações</th>
  </tr>
  <% @production_unity_scope.scope_products.joins(:product).order('products.name').each do |scope_product| %>
    <tr>
      <td><%= scope_product.product.name %></td>

      <td><%= scope_product.amount.present? ? "#{rounded_formated_value(scope_product.amount)} #{ScopeProduct::UNITIES[scope_product.unity]} (s)" : "Não informado" %> </td>
      <td><%= scope_product.area.present? ? rounded_formated_value(scope_product.area) : "Não informado" %></td>
      <td><%= l(scope_product.updated_at) %></td>
      <td><%= link_to "Editar", edit_group_production_unity_production_unity_scope_scope_product_path(@group, @production_unity, @production_unity_scope, scope_product), class: "btn btn-default btn-sm" %></td>
      <td><%= link_to "Remover", [@group, @production_unity, @production_unity_scope, scope_product], method: :delete, class: "btn btn-danger btn-sm" %>
    </tr>
  <% end %>
</table>
<% else %>
  <h3>Não há produtos vinculados a este escopo ainda !  Por favor, adicione no menu ações no canto superior direito </h3>
<% end %>

app/views/groups/production_unity_scopes/edit.html.erb
 <%= link_to 'Pagina ínicial', root_path %> -<%= link_to " #{@group.core.name} -", @group.core if user_type == 4 %> <%= link_to 'Listando grupos', groups_path %> - <%= link_to "Grupo: #{@group.name}", @group %> - <%= link_to 'Listando unidades de produção', group_production_unities_path(@group) %> - <%= link_to @production_unity.name, [@group, @production_unity] %> - <%= "Escopo  #{@production_unity_scope.scope.acronym}" %> - Editando escopo

<br>

<h2>Editando escopo <%= @production_unity_scope.scope.acronym %> de <%= @production_unity.name %></h2>	

 <%= render 'production_unity_form' %>

app/views/groups/production_unity_scopes/new.html.erb
<%= link_to 'Pagina ínicial', root_path %> -<%= link_to " #{@group.core.name} -", @group.core if user_type == 4 %> <%= link_to 'Listando grupos', groups_path %> - <%= link_to "Grupo: #{@group.name}", @group %> - <%= link_to 'Listando unidades de produção', group_production_unities_path(@group) %> - <%= link_to @production_unity.name, [@group, @production_unity] %> - Novo escopo
<h3>Cadastrando novo escopo para <%= @production_unity.name %> </h3>

<hr>

<% if @production_unity.scope_type == 1 %>
  <%= render 'production_unity_form' %>
<% else %>
  <%= render 'agribusiness_form' %>
<% end %>

app/views/groups/production_unity_scopes/show.html.erb
<%= link_to 'Pagina ínicial', root_path %> -<%= link_to " #{@group.core.name} -", @group.core if user_type == 4 %> <%= link_to 'Listando grupos', groups_path %> - <%= link_to "Grupo: #{@group.name}", @group %> - <%= link_to 'Listando unidades de produção', group_production_unities_path(@group) %> - <%= link_to @production_unity.name, [@group, @production_unity] %> - Escopo <%= @production_unity_scope.scope.acronym %>



<% if @production_unity.scope_type == 1 %>
  <%= render 'production_unity_show' %>
<% else %>
  <%= render 'agribusiness_show' %>
<% end %>