config/routes.rb
Rails.application.routes.draw do
  resource :excluded_data, only: [:show] do
    resources :farmers, only: [:index], module: :excluded_data
    resources :production_unities, only: [:index], module: :excluded_data
    resources :groups, only: [:index], module: :excluded_data
  end

  # Help
  get '/help/reduce_pdf_size'

  get 'document_access_visualizations/core'

  get 'document_access_visualizations/group'

  get 'document_access_visualizations/documents_farmers_and_production_unities'

  get 'document_access_visualizations/farmer'

  get 'document_access_visualizations/production_unity'

  get 'document_access_visualizations/certificate'

  resources :document_visualizations
  get "/home/search" => "home#search"
  get "/home/report" => "home#report"
  resource :user_sessions
  resource :document_visualization_sessions

  namespace :view_reports do
    get '/view_reports' => 'view_reports#index'
    get '/farmer_reports' => 'farmer_reports#index'
    get '/product_reports' => 'product_reports#index'
    get '/city_reports' => 'city_reports#index'
    get '/production_unity_reports' => 'production_unity_reports#index'
  end

  namespace :reports do
    get 'index'
    get 'quantity'
    get 'annuity'
    get 'certified_members'

    get '/core_reports/actual_situation' => 'core_reports#actual_situation'
    get '/core_reports/products' => 'core_reports#products'
    get '/global_reports/actual_situation' => 'global_reports#actual_situation'
    get '/global_reports/annuity' => 'global_reports#annuity'
    post '/global_reports/certificate_documents' => 'global_reports#certificate_documents'
    get '/group_reports/products' => 'group_reports#products'
  end

  resources :document_approvment, only: [:index, :create]
  resources :dac_approvment, only: [:index, :create]
  resources :pending_documents, only: [:index]

  resource :records, only: [:show] do
    resources :documents, module: :records
    resources :logs, only: [:index], module: :records
    resources :unity_suspension_types, except: [:delete], module: :records
    resources :group_types, except: [:delete], module: :records
    resources :product_categories, except: [:delete], module: :records
    resources :products, except: [:delete], module: :records
    resources :scopes, module: :records
    resources :acronyms, module: :records
    resources :suspension_types, module: :records
  end

  resources :groups, except: :delete do
    resources :change_core, module: :groups, only: [:new, :create]
    resources :send_documents, module: :groups
    resources :dac_documents, module: :groups

    get "/outdateds" => "groups#outdateds"
    post "/update_outdateds" => "groups#update_outdateds"
    get "/group_dacs" => "groups#group_dacs"
    post "/group_dacs" => "groups#create_group_dacs"
    resources :certificate_groups, module: :groups do
      resources :certificate, only: [:index, :show]
    end
    resources :production_unities, module: :groups do
      get 'certificates'
      resources :send_documents, module: :production_unities
      post 'remove_suspension' => 'production_unities#remove_suspension'
      post 'set_updated' => 'production_unities#set_updated'
      resources :production_unity_farmers do
        post "" => "production_unity_farmers#change_responsible"
      end
      resources :production_unity_scopes do
        resources :scope_products, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :unity_suspensions
    end
    resources :set_suplentes, except: [:delete, :edit, :update], module: :groups
    resources :farmers, except: :delete do
      post 'set_updated' => 'farmers#set_updated'

      collection do
        get 'validate_name'
      end
      
      get 'certificates'
      resources :farmer_group_changes, module: :farmers
      resources :dacs, except: [:update, :edit], module: :farmers
      resources :daps, except: [:update, :edit], module: :farmers
      resources :farmer_families, module: :farmers
      resources :send_documents, module: :farmers
      resources :farmer_suspensions, module: :farmers
        post 'remove_suspension' => 'farmers#remove_suspension'
    end
  end

  resources :cores, except: [:delete] do
    resources :core_coordinators, except: [:show, :destroy], module: :cores do
      member do
        patch :update_current
      end
    end
    resources :payments, module: :cores
  end

  resources :system_settings, only: [:index, :edit, :update]

  resources :admin_password_updater

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_authentication
  def index
    @document_count = DocumentSended.where(status: 'pending').count
    @dac_count = DacDocument.where(status: 'pending').count
  end
  def report

  end
  def search
    @query = params[:query]
    
    if @query != ""
      @groups = Group.all.text_search(@query).page(params[:group_page]).per(15)
      @farmers = Farmer.all.text_search(@query).page(params[:farm_page]).per(15)
      @farmer_families = FarmerFamily.all.text_search(@query).page(params[:farmer_family_page]).per(15)
      
      if user_type == 4
        @production_unities = ProductionUnity.all.text_search(@query).page(params[:production_unity_page]).per(15)
      elsif user_type.in? 2..3
        @production_unities = Core.find(current_user).production_unities.text_search(@query).page(params[:production_unity_page]).per(15)
      end

    else
      redirect_to root_path, alert: "Digite o que você deseja procurar."
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_menu_adm.html.erb
  <div class="row">

    <div class="col-md-4">
      <h2>Gerenciar Núcleos</h2>
      <p>Nesta sessão, é possível gerenciar todos os núcleos do sistema.  Em seus sub-menus, é possível adicionar grupos, alterar coordenadores dos grupos, e muito mais. </p>
      <p>
        <%= link_to 'Gerenciar núcleos', cores_path, class: "btn btn-default" %>
      </p>
    </div>

    <div class="col-md-4">
      <h2>Gerenciar Grupos</h2>
      <p>Nesta sessão, é possível gerenciar os grupos, procurar grupos.  Quando um grupo é selecionado, é possível gerenciar seus agricultores, gerar relatórios, alterar informações, etc. </p>
      <p>
        <%= link_to "Gerenciar grupos", groups_path, class: "btn btn-default" %>
      </p>
    </div>

    <div class="col-md-4">
      <h2>Cadastros</h2>
      <p>Nesta sessão é possível gerenciar os cadastros gerais do sistema, como siglas, tipos de grupos, produtos, caregorias de produtos e escopos.</p>
      <p>
        <%= link_to "Ver cadastros", records_path, class: "btn btn-default"%>
      </p>
    </div>

  </div>
  <div class="row">

    <div class = "col-md-4">
      <h2>Logs</h2>
      <p>Nesta sessão, é possível saber tudo que acontece no sistema.  Toda alteração no sistema aparece aqui, até a mais simples</p>
      <p>
        <%= link_to "Ver logs", records_logs_path, class: "btn btn-default" %>
      </p>
    </div>

    <div class = "col-md-4">
      <h2>Relatórios</h2>
      <p>Nesta sessão, saber algumas informações no sistema.  Estas informações podem ser usadas para tomar decisões importantes.</p>
      <p>
        <%= link_to "Ver relatórios", reports_index_path, class: "btn btn-default" %>
      </p>
    </div>

    <div class = "col-md-4">
      <h2>Configurações do Sistema</h2>
      <p>Nesta sessão, é possível realizar a atualização das configurações do sistema.</p>
      <p>
        <%= link_to "Ver configurações", system_settings_path, class: "btn btn-default" %>
      </p>
    </div>

  </div>
  <div class="row">
    <div class="col-md-4">
      <h2>Gerenciar minha senha</h2>
      <p>Nesta sessão, é possível atualizar a sua senha sempre que necessário. </p>
      <p>
        <%= link_to 'Gerenciar senha', new_admin_password_updater_path, class: "btn btn-default" %>
      </p>
    <% if @document_count > 0 || @dac_count > 0%>
    </div>
      <div class="col-md-4">
      <h2>Gerenciar envio de documentos</h2>
      <p>Há <%= @document_count + @dac_count %> documento(s) para serem analisados. </p>
      <p>
        <%= link_to 'Analisar Documentos Enviados', document_approvment_index_path, class: "btn btn-default" %>
      </p>
    </div>
    <% end %>
    <div class = "col-md-4">
      <h2>Gerenciar acesso de visualização de documentos</h2>
      <p>Nesta sessão, é possível gerar um link e uma chave para visualizar os documentos.</p>
      <p>
        <%= link_to "Gerenciar acessos", document_visualizations_path, class: "btn btn-default" %>
      </p>
    </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <h2>Dados excluídos</h2>
        <p>Nesta sessão é possível visualizar os membros, grupos e propriedades que foram excluídas</p>
        <p>
          <%= link_to 'Ver informações excluídas', excluded_data_path, class: 'btn btn-default' %>
        </p>
      </div>
      <div class = 'col-md-4'>
        <h2>Relatórios Dinâmicos</h2>
        <p>Neste sessão é possível fazer relatórios em tempo real</p>
        <p>
          <%= link_to "Ir para relatórios dinâmicos", view_reports_view_reports_path, class: "btn btn-default" %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/home/_menu_core.html.erb
<% @core = Core.find(current_user) %>
<% if @core.core_coordinators.first.nil? %>
	<div class = "alert alert-warning">
	<strong>Atenção!</strong> Este núcleo ainda não tem as informações do coordenador da comissão de Ética do núcleo.  Para adicionar, <%= link_to 'Clique aqui', new_core_core_coordinator_path(@core) %>
	</div>
<% end %>


		<div class="row">
			<div class="col-md-4">
				<h2>Gerenciar Grupos</h2>
				<p>Nesta sessão, é possível gerenciar os grupos, procurar grupos.  Quando um grupo é selecionado, é possível gerenciar seus agricultores, gerar relatórios, alterar informações, etc. </p>
				<p><%= link_to "Gerenciar grupos", groups_path, class: "btn btn-default" %></p>
			</div>
			<div class="col-md-4">
				<h2>Gerenciar coordenadores</h2>
				<p>Nesta sessão, é possível gerenciar os coordenadores do núcleo, adicionar novos, e fazer a listagem dos antigos.</p>
				<p><%= link_to "Gerenciar coordenadores", core_core_coordinators_path(current_user), class: "btn btn-default"%></p>
			</div>
			<div class="col-md-4">
				<h2>Falar com os desenvolvedores</h2>
				<p>Nesta sessão, você receberá todas informações para falar direto com os desenvolvedores.  Será apresentado as instruções de como reportar um <strong>erro</strong> ou pedir uma nova funcionalidade.</p>
				<p><%= link_to "Saiba mais", home_report_path, class: "btn btn-default"%></p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-5">
				<h2>Verificar documentação pendente do núcleo</h2>
				<p>Neste sessão, conseguiremos analisar a documentação pendente dos grupos, membros, agroindustrias e unidades de produção. </p>
				<p><%= link_to "Verificar Documentações Pendentes", pending_documents_path, class: "btn btn-default" %></p>
			</div>
			<div class ="col-md-5">
				<h2>Documentos da OPAC da Rede Ecovida de Agroecologia</h2>
				<p>Estatuto, manual, normas, documentos para adequação e outros documentos de apoio e esclarecimentos necessários para a certificação de orgânicos da Rede</p>
				<p><%= link_to 'Ir para tela de downloads', 'https://drive.google.com/drive/folders/15NyM-eymC6VbOovvAiPEgXesP0EFTqAM?usp=sharing', class: 'btn btn-default', target: :_blank %>
		</div>

app/views/home/_menu_group.html.erb
<p>Ainda não foi implementada nenhuma função para o grupo</p>

app/views/home/index.html.erb
<h1>Pagina inicial</h1>

<% if user_type == 4 %>
  <%= render 'menu_adm' %>
<% elsif user_type == 3 or user_type == 2 %>
  <%= render 'menu_core' %>
<% else user_type == 1 %>
  <%= render 'menu_group' %>
<% end %>

app/views/home/report.html.erb
<fieldset>
	<legend>
		Sobre
	</legend>
	<p>
		Para conversar diretamente com os desenvolvedores, mande um email para <%= link_to "software.ecovida@gmail.com", "mailto:software.ecovida@gmail.com" %>.  Veja abaixo as dicas para o envío do email
	</p>
</fieldset>

<fieldset>
	<legend>
		Sempre se identifique
	</legend>
	<p>No começo da mensagem, diga quem é e de que núcleo você é, assim, facilitando a comunicação e o suporte.  Já no assunto, identifique se é: [Problema] [Sugestão] ou [Suporte]</p>
</fieldset>

<fieldset>
	<legend>Irá reportar um problema?</legend>
	<p>Sempre que for reportar um problema, descreva como chegou a ele, os dados que tentou informar e o que está acontecendo de errado, assim, facilitando o teste e a correção do problema.  Se for possível, tente gravar um vídeo ou tirar alguma foto e mandar por anexo.</p>
</fieldset>

<fieldset>
	<legend>Gostaria de fazer uma sugestão?</legend>
	<p>Se for fazer uma sugestão, explique claramente o que deseja, e o motivo real da sugestão \ alteração.  A sugestão será analizada, e se for víavel, será implementada assim que possível.</p>
</fieldset>

<fieldset>
	<legend>Precisa de ajudar?  Fale conosco</legend>
	<p>Qualquer dúvida sobre a utilização do sistema, você pode entrar em contato conosco, que iremos responder o mais rápido possível</p>
</fieldset>

<%= link_to "Voltar", root_path, class: "btn btn-default" %>

app/views/home/search.html.erb
<h3><%= link_to "Voltar para página inicial", root_path %></h3>

<h3>Resultados da pesquisa de: <%= @query %> </h3>

<% if @groups.count != 0 %>
  <fieldset>
    <legend>Grupos encontrados.</legend>
    <ul>
      <% @groups.each do |group| %>
        <li><%= link_to group.name, group %> que pertence ao núcleo <%= group.core.name %></li>
      <% end %>
    </ul>
    <%= paginate @groups, param_name: :group_page %>
  </fieldset>
<% else %>
  <h4>Não foram encontrados grupos</h4>
<% end %>
<hr>

<% if @farmers.count != 0 %>
  <fieldset>
    <legend>Agricultores encontrados.</legend>
    <ul>
      <% @farmers.each do |farmer| %>
        <li><%= link_to farmer.name, [farmer.group, farmer] %> que pertence ao grupo <%= link_to farmer.group.name, farmer.group %></li>
      <% end %>
    </ul>
    <%= paginate @farmers, param_name: :farm_page %>
  </fieldset>
<% else %>
  <h4>Não foram encontrados agricultores</h4>
<% end %>
<hr>

<% if @farmer_families.count != 0 %>
  <fieldset>
    <legend>Familiares de agricultores encontrados.</legend>
    <ul>
      <% @farmer_families.each do |farmer_family| %>
        <li><%= link_to farmer_family.name, [farmer_family.farmer.group, farmer_family.farmer, farmer_family] %>, familiar de <%= link_to farmer_family.farmer.name, [farmer_family.farmer.group, farmer_family.farmer] %>, 
	  que pertence ao grupo <%= link_to farmer_family.farmer.group.name, farmer_family.farmer.group %></li>
      <% end %>
    </ul>
    <%= paginate @farmer_families, param_name: :farmer_family_page %>
  </fieldset>
<% else %>
  <h4>Não foram encontrados agricultores</h4>
<% end %>
<hr>

<% if @production_unities.count != 0 %>
  <fieldset>
    <legend>Unidades de produções e agroindustrias encontradas.</legend>
    <ul>
      <% @production_unities.each do |pu| %>
        <li><%= link_to pu.name, [pu.group, pu] %> que pertence ao grupo <%= link_to pu.group.name, pu.group %> .  Está propriedade tem como responsável o <%= link_to pu.responsible.name, [pu.responsible.group, pu.responsible] %></li>
      <% end %>
    </ul>
    <%= paginate @production_unities, param_name: :production_unity_page %>
  </fieldset>
<% else %>
  <h4>Não foram encontradas undades de produções nem agroindustrias</h4>
<% end %>
<hr>