config/routes.rb
Rails.application.routes.draw do
  resource :excluded_data, only: [:show] do
    resources :farmers, only: [:index], module: :excluded_data
    resources :production_unities, only: [:index], module: :excluded_data
    resources :groups, only: [:index], module: :excluded_data
  end

  # Help
  get '/help/reduce_pdf_size'

  get 'document_access_visualizations/core'

  get 'document_access_visualizations/group'

  get 'document_access_visualizations/documents_farmers_and_production_unities'

  get 'document_access_visualizations/farmer'

  get 'document_access_visualizations/production_unity'

  get 'document_access_visualizations/certificate'

  resources :document_visualizations
  get "/home/search" => "home#search"
  get "/home/report" => "home#report"
  resource :user_sessions
  resource :document_visualization_sessions

  namespace :view_reports do
    get '/view_reports' => 'view_reports#index'
    get '/farmer_reports' => 'farmer_reports#index'
    get '/product_reports' => 'product_reports#index'
    get '/city_reports' => 'city_reports#index'
    get '/production_unity_reports' => 'production_unity_reports#index'
  end

  namespace :reports do
    get 'index'
    get 'quantity'
    get 'annuity'
    get 'certified_members'

    get '/core_reports/actual_situation' => 'core_reports#actual_situation'
    get '/core_reports/products' => 'core_reports#products'
    get '/global_reports/actual_situation' => 'global_reports#actual_situation'
    get '/global_reports/annuity' => 'global_reports#annuity'
    post '/global_reports/certificate_documents' => 'global_reports#certificate_documents'
    get '/group_reports/products' => 'group_reports#products'
  end

  resources :document_approvment, only: [:index, :create]
  resources :dac_approvment, only: [:index, :create]
  resources :pending_documents, only: [:index]

  resource :records, only: [:show] do
    resources :documents, module: :records
    resources :logs, only: [:index], module: :records
    resources :unity_suspension_types, except: [:delete], module: :records
    resources :group_types, except: [:delete], module: :records
    resources :product_categories, except: [:delete], module: :records
    resources :products, except: [:delete], module: :records
    resources :scopes, module: :records
    resources :acronyms, module: :records
    resources :suspension_types, module: :records
  end

  resources :groups, except: :delete do
    resources :change_core, module: :groups, only: [:new, :create]
    resources :send_documents, module: :groups
    resources :dac_documents, module: :groups

    get "/outdateds" => "groups#outdateds"
    post "/update_outdateds" => "groups#update_outdateds"
    get "/group_dacs" => "groups#group_dacs"
    post "/group_dacs" => "groups#create_group_dacs"
    resources :certificate_groups, module: :groups do
      resources :certificate, only: [:index, :show]
    end
    resources :production_unities, module: :groups do
      get 'certificates'
      resources :send_documents, module: :production_unities
      post 'remove_suspension' => 'production_unities#remove_suspension'
      post 'set_updated' => 'production_unities#set_updated'
      resources :production_unity_farmers do
        post "" => "production_unity_farmers#change_responsible"
      end
      resources :production_unity_scopes do
        resources :scope_products, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :unity_suspensions
    end
    resources :set_suplentes, except: [:delete, :edit, :update], module: :groups
    resources :farmers, except: :delete do
      post 'set_updated' => 'farmers#set_updated'

      collection do
        get 'validate_name'
      end
      
      get 'certificates'
      resources :farmer_group_changes, module: :farmers
      resources :dacs, except: [:update, :edit], module: :farmers
      resources :daps, except: [:update, :edit], module: :farmers
      resources :farmer_families, module: :farmers
      resources :send_documents, module: :farmers
      resources :farmer_suspensions, module: :farmers
        post 'remove_suspension' => 'farmers#remove_suspension'
    end
  end

  resources :cores, except: [:delete] do
    resources :core_coordinators, except: [:show, :destroy], module: :cores do
      member do
        patch :update_current
      end
    end
    resources :payments, module: :cores
  end

  resources :system_settings, only: [:index, :edit, :update]

  resources :admin_password_updater

  root 'home#index'

end

app/models/report.rb
class Report
	# ~ Quantity ~ #
		# ~ - Farmers - ~#
	def self.farmers_with_dap
		farmers = []
		Farmer.all.each do |farmer|
			if farmer.dap_due_date
				farmers << farmer if farmer.dap_due_date > Time.now()
			end
		end

		Farmer.where(id: farmers.map{|farmer|  farmer.id}).count
	end

	def self.farmers_with_dac
		farmers = []
		Farmer.all.each do |farmer|
			if farmer.dac_due_date
				farmers << farmer if farmer.dac_due_date > Time.now() + 365
			end
		end

		Farmer.where(id: farmers.map{|farmer|  farmer.id}).count
	end

	def self.farmers_suspended(count= true)
		farmers = []
		Farmer.all.each do |farmer|
			farmers << farmer if farmer.is_suspended?
		end

		return Farmer.where(id: farmers.map{|farmer| farmer.id}).count if count
		Farmer.where(id: farmers.map{|farmer| farmer.id})
	end

	def self.documents_ok_without_suspension
		farmers = []
		farmers_suspended(false).each do |farmer|
			farmers << farmer if farmer.documents_ok?
		end

		Farmer.where(id: farmers.map{|farmer| farmer.id}).count
	end

	def self.farmer_with_sig_org_equals status
		farmers = []
		Farmer.all.each do |farmer|
			farmers << farmer if farmer.sig_org_status == status
		end

		Farmer.where(id: farmers.map{|farmer| farmer.id}).count
	end

		# ~ - Fim farmers - ~ #
		# ~ - Inicio Production Unity ~ #

	def self.production_unity_suspended
		pus = []
		ProductionUnity.all.each do |pu|
			pus << pu if pu.is_suspended?
		end

		ProductionUnity.where(id: pus.map{|pu| pu.id}).count
	end


		# ~ - Fim Production Unity ~ #
	# ~ Fim QUantity ~ #
end

app/controllers/reports/core_reports_controller.rb
module Reports
  class CoreReportsController < ApplicationController
    before_action :set_core

    def actual_situation
      Reports::ActualSituationReport.new(@core).process(params[:core][:email])

      head :ok
    end

    def products
      Reports::ProductsReport.new(@core.first.groups).process(params[:core][:email])

      head :ok
    end

    private

    def set_core
      @core = Core.where(id: params[:core][:id])
    end
  end
end

app/controllers/reports/global_reports_controller.rb
module Reports
  class GlobalReportsController < ApplicationController
    before_action :require_admin

    def actual_situation
      Reports::ActualSituationReport.new(Core.all).process(params[:core][:email])

      head :ok
    end

    def certificate_documents
      Reports::CertificatesReport.new(certificate_params.deep_symbolize_keys).process

      redirect_to reports_index_path, notice: 'Seu relatório será enviado para seu e-mail'
    end

    def annuity
      Reports::AnnuityReport.new(Core.all.order(:name), params[:year]).process(params[:core][:email])

      head :ok
    end

    private

    def certificate_params
      params.require(:report).permit(:from, :to, :email, :core_id)
    end
  end
end

app/controllers/reports/group_reports_controller.rb
module Reports
  class GroupReportsController < ApplicationController
    before_action :set_group

    def products
      report = Reports::ProductsReport.new(@group).process(params[:group][:email])

      head :ok
    end

    private

    def set_group
      @group = Group.where(id: params[:group][:id])
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_admin
  
  def index
  end

  def quantity
  end

  def certified_members
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
	def percent_of(total, amount)
	if total > 0
		"#{((amount * 100) / total).round(2)}%"
	else
		"0%"
	end
	end
end

app/views/reports/annuity.html.erb
<%= link_to "ìnicio", root_path %> - <%= link_to "Relatórios", reports_index_path %> - Relatório das anuidades

<table class="table">
  <tr>
    <th>Núcleo</th>
    <th>Total á pagar</th>
    <th>Pago</th>
    <th>À pagar</th>
  </tr>
  <% @cores.each do |core| %>
  <tr>
    <td><%= link_to core[:core_name], core_path(core[:core_id]) %></td>
    <td><%= number_to_currency core[:total] %></td>
    <td><%= number_to_currency core[:to_pay] %></td>
    <td><%= number_to_currency core[:payed] %></td>
  </tr>
  <% end %>
</table>

app/views/reports/certified_members.html.erb
<%=
  create_breadcumbs([
    { url: root_path, text: 'Página inicial' },
    { url: reports_index_path, text: "Relatórios" },
    { url: nil, text: "Relatório de membros certificados para o ministério da agricultura" }
  ])
%>

<%= simple_form_for :report, url: reports_global_reports_certificate_documents_url do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :kind, as: :select, label: 'Tipo de Relatório', collection: ['Apenas um núcleo', 'Todos os núcleos'],
       include_blank: false, input_html: { class: 'JS-certified-members' } %>
    </div>
    <div class="col-md-6">
      <%= f.input :core_id, as: :select,  label: 'Núcleo', collection: Core.all %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :use_date, as: :select,  label: 'Entre datas', collection: ['Escolher Data', 'Ano Passado'], include_blank: false %>
    </div>
    <div class="col-md-6">
      <%= f.input :email, as: :string, label: 'Seu Email:' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :from, as: :string, label: 'De:', input_html: { class: 'form_date' } %>
    </div>
    <div class="col-md-3">
      <%= f.input :to, as: :string, label: 'Para:', input_html: { class: 'form_date' } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.submit 'Gerar relatório', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/reports/index.html.erb
<%= link_to "Ínicio", root_path %> - Relatórios

<h1>Relatórios</h1>
<p>Por favor, escolha o tipo de relatório que você deseja</p>

<ul>
	<li><%= link_to "Relatório de quantidade - Aqui você saberá quantos agricultores, grupos, nucleos, entre outros, que estão cadastrados no sistema", reports_quantity_path %></li>
	<li><%= link_to "Relatório da situação atual do cadastro", '#', class: 'actual_situation' %></li>
	<li><%= link_to "Relatório de anuidades", '#', class: 'annuity' %></li>
	<li><%= link_to "Relatório de membros certificados para ministério da agricultura", reports_certified_members_path %></li>
</ul>

<%= render partial: 'show_report', locals: {button_name: 'actual_situation', model: Core.new, path: reports_global_reports_actual_situation_path } %>
<%= render partial: 'show_report', locals: {button_name: 'annuity', model: Core.new, path: reports_global_reports_annuity_path, need_year: true } %>

app/views/reports/quantity.html.erb
<%= link_to "ìnicio", root_path %> - <%= link_to "Relatórios", reports_index_path %> - Relatório de quantidade

<h1>Relatório de quantidade</h1>
<fieldset>
	<legend>Agricultores</legend>
	<ul>
	<li>Numero total de agricultores: <%= @total_farmers = Farmer.all.count %> </li>
	<li>Numero total de agricultores com D.A.P em dia: <%= @with_dap = Report.farmers_with_dap %> (<%= percent_of(@total_farmers, @with_dap) %> do total)</li>
	<li>Numero total de agricultores com D.A.C em dia: <%= @with_dac = Report.farmers_with_dac %> (<%= percent_of(@total_farmers, @with_dac) %> do total)</li>
	<li>Numero de familhares cadastrados: <%= FarmerFamily.all.count %></li>
	<li>Agricultores suspensos: <%= @suspendeds = Report.farmers_suspended %> (<%= percent_of(@total_farmers, @suspendeds) %> do total)</li>
	<li>Agricultores não suspensos com todos documentos em dia (Inclusive D.A.P): <%= @documents_ok = Report.documents_ok_without_suspension %> (<%= percent_of((@total_farmers - @suspendeds), @documents_ok) %> do total de agricultores não suspensos)</li>
	<li>Agricultores não adicionados no Sig.Org: <%= @farmer_not_updated =  Report.farmer_with_sig_org_equals 'Não adicionado' %> (<%= percent_of(@total_farmers, @farmer_not_updated) %> do total)</li>
	<li>Agricultores atualizados no Sig.Org: <%= @farmer_updated =  Report.farmer_with_sig_org_equals 'Atualizado' %> (<%= percent_of(@total_farmers, @farmer_updated) %> do total)</li>
	<li>Agricultores desatualizados no Sig.Org: <%= @farmer_outdateds =  Report.farmer_with_sig_org_equals 'Desatualizado' %> (<%= percent_of(@total_farmers, @farmer_outdateds) %> do total)</li>
	<ul>
</fieldset>


<fieldset>
	<legend>Unidades de produção</legend>
	<ul>
		<li>Numero total de unidade de produções e agroindustrias: <%= @total_production_unity_and_agro = ProductionUnity.all.count %></li>
		<li>Numero total de unidades de produções: <%= @total_production_unity = ProductionUnity.where(scope_type: 1).count %> (<%= percent_of(@total_production_unity_and_agro, @total_production_unity) %> do total)</li>
		<li>Numero total de agroindustrias: <%= @total_agribusiness = ProductionUnity.where(scope_type: 2).count %> (<%= percent_of(@total_production_unity_and_agro, @total_agribusiness) %> do total)</li>
		<li>Unidades de produções ou agroindustrias suspensas: <%= @total_suspended = Report.production_unity_suspended %> (<%= percent_of(@total_production_unity, @total_suspended) %> do total)</li>
		<% Scope.all.each do |scope| %>
			<% if scope.scope_type == 1 %>
				<li>Numero de unidades de produção com o escopo <%= scope.name %>(<%= scope.acronym %>): <%= @atual_scope = ProductionUnityScope.where(scope_id: scope.id).count %> (<%= percent_of(@total_production_unity, @atual_scope )%>)</li>
			<% else %>
				<li>Numero de agroindustrias com o escopo <%= scope.name %>(<%= scope.acronym %>): <%= @atual_scope = ProductionUnityScope.where(scope_id: scope.id).count %> (<%= percent_of(@total_production_unity, @atual_scope )%>)</li>
			<% end %>
		<% end %>
	</ul>

</fieldset>

<fieldset>
	<legend>Outros</legend>
	<ul>
		<li>Quantidade de produtos cadastrados: <%= Product.all.count %></li>
		<li>Quantidade de categorias de produtos cadastradas: <%= ProductCategory.all.count %></li>
	</ul>
</fieldset>